/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Profile_CONSTANTS_H
#define Profile_CONSTANTS_H

#include "Profile_types.h"



class ProfileConstants {
 public:
  ProfileConstants();

};

extern const ProfileConstants g_Profile_constants;



#endif
